6000 REM WWINSTR (WORLD WAR INSTRUCTIONS)
6060 REM 5-20-78 GH
6100 PRINT
6110 PRINT "THE GAME CONSISTS OF TEN COUNTRIES:"
6130 PRINT "1) NORTH AMERICA";TAB(41);"2) AUSTRALIA"
6140 PRINT "3) SOUTH AMERICA";TAB(41);"4) RUSSIA"
6150 PRINT "5) JAPAN";TAB(41);"6) AFRICA"
6160 PRINT "7) KOREA";TAB(41);"8) CHINA"
6170 PRINT "9) GREENLAND";TAB(41);"10) ENGLAND"
6180 PRINT
6190 PRINT "THERE ARE FIVE DEFENSES PER COUNTRY:"
6210 PRINT "1) TROOPS"
6220 PRINT "2) PLANES"
6230 PRINT "3) ARTILLERY"
6240 PRINT "4) TANKS"
6250 PRINT "5) MISSLES"
6260 PRINT
6270 PRINT "EACH DEFENSE MAY RESIDE ON ONE SHORE:"
6290 PRINT "1) NORTH SHORE"
6300 PRINT "2) SOUTH SHORE"
6310 PRINT "3) EAST  SHORE"
6320 PRINT "4) WEST  SHORE"
6330 PRINT
6333 INPUT "HIT ANY KEY THEN RETURN TO CONTINUE";A$
6335 PRINT
6340 REM CONTINUE W/FLEX
6350 PRINT "THE COMMANDS AVAILABLE TO YOU ARE:"
6370 PRINT "1) SHOW COUNTRY STATUS"
6380 PRINT "2) TRANSPORT DEFENSES"
6390 PRINT "3) SHOW GLOBAL STATUS"
6400 PRINT "4) PERFORM A SPY MISSION"
6410 PRINT "5) BEGIN ATTACK"
6420 PRINT
6430 INPUT "DO YOU WANT THE COMMANDS EXPLAINED";A$
6435 PRINT:PRINT
6440 IF LEFT$(A$,1)="N"GOTO 1125
6460 PRINT "SHOW COUNTRY STATUS (1) - THE COMPUTER WILL RESPOND WITH"
6470 PRINT "YOUR DEFENSE STATUS IN A PARTICULAR COUNTRY.  IF YOU"
6480 PRINT "CHOOSE A COUNTRY IN WHICH YOU HAVE NO DEFENSES, ZEROES"
6490 PRINT "WILL APPEAR AFTER EACH DEFENSE IS DISPLAYED."
6500 PRINT
6510 PRINT "SHOW GLOBAL STATUS (3) - THE GLOBAL STATUS WILL DISPLAY"
6520 PRINT "BOTH THE QUANITY OF TROOPS THAT BOTH YOU AND THE ENEMY"
6530 PRINT "HAVE IN EACH COUNTRY AND WHO IS IN CONTROL OF IT."
6540 PRINT "IT DOES NOT TELL YOU WHAT SHORE THEY ARE LOCATED ON."
6550 PRINT
6560 PRINT "PERFORM SPY MISSION (4) - THIS COMMAND WILL SHOW YOU THE"
6570 PRINT "LOCATION OF ALL, OR PART, OF THE ENEMY'S DEFENSES ON ANY"
6580 PRINT "COUNTRY SPECIFIED.  IT COSTS YOU TEN PLANES TO GAIN THIS"
6590 PRINT "INFORMATION.  THEY MAY BE SHOT DOWN BEFORE ANY INFO"
6600 PRINT "IS GAINED."
6610 PRINT
6620 PRINT "TRANSPORT DEFENSES (2) - THIS COMMAND WILL TRANSPORT ANY"
6630 PRINT "AMOUNT OF EACH OF THE FIVE DEFENSES TO ANY SHORE OF ANY"
6640 PRINT "COUNTRY.  WITHIN A COUNTRY, ALL QUANTITIES OF A DEFENSE"
6650 PRINT "MUST BE MOVED AT ONE TIME."
6660 PRINT
6670 INPUT "HIT ANY KEY THEN RETURN TO CONTINUE";A$
6680 PRINT
6700 PRINT "BEGIN ATTACK (5) - THIS COMMAND STARTS THE ATTACK.  IF"
6710 PRINT "ONE HAS MORE THAN ONE AND A HALF TIMES OF THE DEFENSES,"
6720 PRINT "THE BATTLE IS OVER AND THE WINNER GAINS THE REMAINING"
6730 PRINT "DEFENSES FOR ITS SIDE."
6740 PRINT
6750 PRINT "STRATEGY - TROOPS ARE THE MOST POWERFUL DEFENSE THERE IS"
6760 PRINT "IN THE GAME.  IT IS A GOOD IDEA WHEN STARTING THE GAME,"
6770 PRINT "TO ATTACK THE COUNTRY WITH THE SMALLEST NUMBER OF TROOPS"
6780 PRINT "FIRST. SENDING A FEW SPY MISSIONS IS WORTH THE PLANES TO"
6790 PRINT "FIND OUT WHERE THE DEFENSES ARE HIDING.  IF THERE ARE"
6800 PRINT "MANY DEFENSES ON A SHORE, IT IS GOOD PRACTICE TO SEND"
6810 PRINT "MANY DEFENSES IN RETURN.  KEEP IN MIND THAT IF YOU SEND"
6820 PRINT "TOO MANY TANKS, FOR EXAMPLE, THE EXCESS LEFT OVER MAY BE"
6830 PRINT "CAPTURED BY THE ENEMY TO BE USED AGAINST YOU DURING THE"
6840 PRINT "SAME ATTACK ON THE SHORE.  THE CASUALTIES CALCULATION IS"
6850 PRINT "BASED UPON THE NUMBER OF DEFENSES RESIDING ON THE SHORE"
6860 PRINT "UNDER ATTACK. SENDING 105,000 TROOPS TO DESTROY 30 TANKS"
6870 PRINT "OR SENDING 60,000 TROOPS TO DESTROY 30 TANKS WILL MOST"
6880 PRINT "LIKELY CAUSE YOU TO WIN IN BOTH CASES, BUT YOUR LOSES"
6890 PRINT "FOR THE LARGER AMOUNT OF TROOPS WILL BE MUCH GREATER."
6910 INPUT "HIT ANY KEY THEN RETURN TO CONTINUE";A$
6915 PRINT
6920 PRINT "ANYWHERE FROM 0 TO 33% OF YOUR DEFENSES CAN BE LOST IN"
6930 PRINT "THE FIRST BATTLE.  THIS IS WHY COMBINING ALL OF YOUR"
6940 PRINT "DEFENSES FROM YOUR FIVE COUNTRIES AND THEN ATTACKING"
6950 PRINT "WON'T WORK.  YOU MAY WIN THE FIRST TWO OR THREE"
6960 PRINT "COUNTRIES, BUT YOUR LOSSES WILL BE TOO GREAT"
6970 PRINT "TO FINISH THE GAME.  AFTER GAINING COUNTRIES FROM BATTLE"
6980 PRINT "DON'T LEAVE YOUR DEFENSES SPREAD ALL OVER THE WORLD. YOU"
6990 PRINT "MAY FORGET ABOUT THEM AND LOSE MANY BATTLES BECAUSE YOU"
7000 PRINT "DON'T HAVE ENOUGH DEFENSES TO WIN WITH A CAPTURE."
7010 PRINT "    SINCE TROOPS ARE THE MOST POWERFUL OF THE DEFENSES,"
7020 PRINT "AVOID GOING INTO BATTLE WITH AN EVEN NUMBER OF TROOPS."
7030 PRINT "IF YOU DON'T LOSE YOU'LL WIND UP WITH A FIGHT TO THE FINISH"
7040 PRINT "LOSING THOUSANDS OF TROOPS AND COMING OUT OF THE BATTLE"
7050 PRINT "NOT PREPARED FOR THE NEXT ONE.  IT IS VERY DIFFICULT TO"
7060 PRINT "CAPTURE TROOPS WITH ANY OTHER DEFENSE, BUT DEFENSES MAY"
7070 PRINT "REDUCE THE NUMBER OF TROOPS IN BATTLE FROM 0 TO 1000"
7080 PRINT "TROOPS PER ATTACK. DON'T REDUCE THE NUMBER OF TROOPS TOO"
7090 PRINT "GREATLY BY OTHER DEFENSES BEFORE ATTACKING; THE TROOPS"
7100 PRINT "YOU ARE KILLING MIGHT BE YOUR OWN."
7110 PRINT
7120 INPUT "HIT ANY KEY THEN RETURN TO CONTINUE";A$
7125 PRINT "COMPUTER WORKING..."
7130 RETURN: REM END OF INSTRUCTIONS; RETURN TO CALLING GOSUB